### PR TITLE
Add BLTouch support

### PR DESCRIPTION
**Pull request by nmsmith22389**
Added support for BLTouch probes as a virtual endstop.

### CODE REVIEW

**Comment by Surion79** [comment]
I think you can cut the comments out like in all the other probe files. (You can't edit the file there anyway)
Otherwise it looks fine for me

**Comment by agios** [comment]
Functionality wise looks good!

**Comment by nmsmith22389** [comment]
> I think you can cut the comments out like in all the other probe files. (You can't edit the file there anyway)
> 
> Otherwise it looks fine for me

I figured... _(I have a tendancy to over annotate 🤓)_

I'll get rid of them and push the changes.

**Comment by Frix-x** [comment]
I'll wait for your changes and then I'll merge! So I assume that at the end, no changes were needed in the generic_probe.cfg macro for the specificity of the BLTouch?

Thanks for your PR :)

**Comment by tristanmcpherson** [comment]
Maybe add a comment outlining that if they need to define a safe homing position, it will by default use zero_reference_position if defined on the bed mesh, otherwise it will try to z home at the center. The reason I bring this up is a bit tangential, but when I was setting up BLTouch I crashed my hotend a few times because it was homing at 0, 0 due to my improper setting of zero_reference_position.

**Comment by tristanmcpherson** [comment]
Do we also want to add support for `ACTIVATE_PROBE` and `DEACTIVATE_PROBE`?

**Comment by Frix-x** [comment]
> Do we also want to add support for `ACTIVATE_PROBE` and `DEACTIVATE_PROBE`?

Yes, if the BLTouch needs some specific actions to be done before it can probe, if this is not the case, there is nothing to add in here.

In fact, these macros are called everywhere in Klippain whenever probing is needed. In the case of a dockable probe like a klicky, it will call the take probe and dock probe macros. In the case of a TAP that needs to probe at a safe temperature, it will lower the temperature as needed and raise it again afterwards. For an inductive probe, nothing specific is needed, so the macro doesn't have anything that belongs to that type of probe.

Since I'm not very aware of how a BLTTouch work exactly, I'm not sure if anything is needed in these macros. Maybe to deploy the needle? Not sure if this is done automatically by Klipper or not.

**Comment by agios** [comment]
The needle is indeed automatically deployed by Klipper, no further actions should be needed in activate/deactivate. Both z endstop and tilt have been working fine for a week for me without any modification.

**Comment by nmsmith22389** [comment]
Yeah, Klipper handles all of that so it should all be fine as is.

I use these changes on my printer with a BLTouch and everything works as intended.

The only thing I'm not entirely sure about is Klippain compatibility/interactions with `[safe_z_home]`. Specifically options like `home_xy_position` and `z_hop`. I haven't messed around with it yet.

**Comment by Frix-x** [comment]
> The only thing I'm not entirely sure about is Klippain compatibility/interactions with `[safe_z_home]`. Specifically options like `home_xy_position` and `z_hop`. I haven't messed around with it yet.

This is ok as it is handled by the homing_override Klipper section and I think the behavior should be pretty close to that of the inductive probe :)

**Review by Frix-x — APPROVED** [review]

**Pull request merged**
