### PR TITLE
Ercf prime line clog detection

### PR DESCRIPTION
**Pull request by Surion79**
now correct against develop

### CODE REVIEW

**Comment by Benoitone** [comment]
Hello,
Don't you think it is safer in this case to use the variable generated by the HH version of the ercf?
{% if printer.ercf.enabled|int == 1 %}
Because I'm not sure that ERCF_TEST_CONFIG exists in the version of ette?

**Comment by Surion79** [comment]
The _new_ prime line function triggers automated clog detection in HH. i tested v4 preview and it clogged unless i deactivated it with this code.
I discussed with Frix yesterday about ercf integration and it needs some overhaul in general. ERCF "vanilla" vs. HH. Since for HH the variable ercf_enabled is also mandatory in the current state of Klippain, i kept it like this. I changed it to reflect it. but since my printer is printing, i can't test it.

**Comment by Benoitone** [comment]
Ok, I didn't test V4.
The ercf_enabled isn't include by default in HH unlike ercf.enabled, that's why I was making this remark.

**Comment by Surion79** [comment]
With ercf_enabled not set, HH doesn't work, since initial loading of filament is based on ercf_enabled alone.

**Comment by Benoitone** [comment]
It's true but there is a bug in your macro with klippain stock ercf

**Comment by Surion79** [comment]
What is the bug? Code runs only when HH is used. 🤔 by your definition. The code itself is tested with HH. Not testable with stock ercf since stock ercf does not run the code.

**Comment by Frix-x** [comment]
Mhmm ok... As I don't have an ERCF right now I do not have any arguments for one of the other. So I would say that this will be paused for now until there is a real and proper support of the ERCF and not just patchs like that.

So, as the Ette version is not updated anymore and the community tend to go toward the currently developped ERCF v3 of moggieuk. I would go for an HH only integration and remove the old one. Are you both ok with that?

If the answer is yes, then we will need to redevelop something from zero and better adapted to how Klippain is designed :)

**Comment by Benoitone** [comment]
> What is the bug? Code runs only when HH is used. 🤔 by your definition. The code itself is tested with HH. Not testable with stock ercf since stock ercf does not run the code.

If someone wants to use the ercf with the version that is already integrated into klippain ERCF_TEST_CONFIG is not possible. This is a novelty of HH. For the version of this, it would be better to use SET_FILAMENT_SENSOR SENSOR=encoder_sensor ENABLE=0 or 1 to desactivate clog detection.

**Comment by Surion79** [comment]
Set filament sensor does not work for HH encoder. It is an own section. This fix is only for HH. Look at the last commit. It can only be reached by HH.
If you need a an additional fix for stock ercf, you can add it here and i update the PR.

**Comment by Frix-x** [comment]
> Well, I need to override then the function. Currently HH will NOT work with Klippain v4! It is important to note this in the release notes.

Well I understand that. Klippain is an hobby project, so I see no problem delaying the release of the v4 for a couple days waiting to get a proper ERCF support :)

**Comment by Benoitone** [comment]
> Set filament sensor does not work for HH encoder. It is an own section. This fix is only for HH. Look at the last commit. It can only be reached by HH.
> If you need an additional fix for stock ercf, you can add it here and i update the PR.

Sorry... I didn't see you set a new ercf_enabled variable different from the other one in klippain

**Comment by Frix-x** [comment]
That's ok for me at least :)

**Comment by Benoitone** [comment]
@Surion79 
Can you test this?
```
[gcode_macro _MODULE_PRIMELINE]
gcode:
    # Set vars
    {% set St = printer["gcode_macro _USER_VARIABLES"].travel_speed * 60 %}
    {% set Sz = printer["gcode_macro _USER_VARIABLES"].z_drop_speed * 60 %}
    {% set prime_line_x, prime_line_y = printer["gcode_macro _USER_VARIABLES"].prime_line_xy|map('float') %}
    {% set prime_line_length = printer["gcode_macro _USER_VARIABLES"].prime_line_length|float %}
    {% set prime_line_flowrate = printer["gcode_macro _USER_VARIABLES"].prime_line_flowrate|float %}

    {% set max_extrude_cross_section = printer.configfile.settings.extruder.max_extrude_cross_section | float %}
    {% set Sp = (prime_line_flowrate / max_extrude_cross_section) * 60 | float %}
	{% set ercf_enabled = printer["gcode_macro _USER_VARIABLES"].ercf_enabled %}
    {% set verbose = printer["gcode_macro _USER_VARIABLES"].verbose %}

    {% if ercf_enabled and printer.ercf.enabled|int == 1 %}
        {% set clog_detection = printer.ercf.clog_detection %}
        {% if clog_detection > 0 %}
            {% if verbose %}
                RESPOND MSG="Deactivate ercf HH clog detection for primeline"
            {% endif %}
            ERCF_TEST_CONFIG enable_clog_detection=0
	{% elif ercf_enabled %}
        {% if printer.ercf.clog_detection|int == 1 %}
            {% if verbose %}
                RESPOND MSG="Deactivate encoder sensor for Clog detection +/- EndlessSpool"
            {% endif %}
            SET_FILAMENT_SENSOR SENSOR=encoder_sensor ENABLE=0
        {% endif %}
    {% endif %}

    G91
    M83
    G1 Z5 F{Sz}

    # Starting position
    G90
    G0 X{prime_line_x} Y{prime_line_y} F{St}
    G1 Z0.6 F{Sz|int / 2}

    # Add pressure in the nozzle
    G92 E0
    G1 E18 F300

    # Prime line
    G92 E0
    G1 Y{prime_line_y + prime_line_length} E{prime_line_length} F{Sp}

    # Retract and Z-hop
    G92 E0
    G1 E-0.2 F2100
    G92 E0
    G1 Z3 F{Sz}
    M400

    {% if ercf_enabled and printer.ercf.enabled|int == 1 %}
       {% if clog_detection > 0 %}
            {% if verbose %}
                RESPOND MSG="Reactivate ercf HH clog detection after primeline"
            {% endif %}
            ERCF_TEST_CONFIG enable_clog_detection={clog_detection}
        {% endif %}
	{% elif ercf_enabled %}
		{% if printer.ercf.clog_detection|int == 1 %}
            {% if verbose %}
                RESPOND MSG="Reactivate encoder sensor for Clog detection +/- EndlessSpool"
            {% endif %}
            SET_FILAMENT_SENSOR SENSOR=encoder_sensor ENABLE=1
        {% endif %}
    {% endif %}
```

**Comment by Benoitone** [comment]
@Surion79 
Can you test this?
```
[gcode_macro _MODULE_PRIMELINE]
gcode:
    # Set vars
    {% set St = printer["gcode_macro _USER_VARIABLES"].travel_speed * 60 %}
    {% set Sz = printer["gcode_macro _USER_VARIABLES"].z_drop_speed * 60 %}
    {% set prime_line_x, prime_line_y = printer["gcode_macro _USER_VARIABLES"].prime_line_xy|map('float') %}
    {% set prime_line_length = printer["gcode_macro _USER_VARIABLES"].prime_line_length|float %}
    {% set prime_line_flowrate = printer["gcode_macro _USER_VARIABLES"].prime_line_flowrate|float %}

    {% set max_extrude_cross_section = printer.configfile.settings.extruder.max_extrude_cross_section | float %}
    {% set Sp = (prime_line_flowrate / max_extrude_cross_section) * 60 | float %}
	{% set ercf_enabled = printer["gcode_macro _USER_VARIABLES"].ercf_enabled %}
    {% set verbose = printer["gcode_macro _USER_VARIABLES"].verbose %}

    {% if ercf_enabled and printer.ercf.enabled|int == 1 %}
        {% set clog_detection = printer.ercf.clog_detection %}
        {% if clog_detection > 0 %}
            {% if verbose %}
                RESPOND MSG="Deactivate ercf HH clog detection for primeline"
            {% endif %}
            ERCF_TEST_CONFIG enable_clog_detection=0
	{% elif ercf_enabled %}
        {% if printer.ercf.clog_detection|int == 1 %}
            {% if verbose %}
                RESPOND MSG="Deactivate encoder sensor for Clog detection +/- EndlessSpool"
            {% endif %}
            SET_FILAMENT_SENSOR SENSOR=encoder_sensor ENABLE=0
        {% endif %}
    {% endif %}

    G91
    M83
    G1 Z5 F{Sz}

    # Starting position
    G90
    G0 X{prime_line_x} Y{prime_line_y} F{St}
    G1 Z0.6 F{Sz|int / 2}

    # Add pressure in the nozzle
    G92 E0
    G1 E18 F300

    # Prime line
    G92 E0
    G1 Y{prime_line_y + prime_line_length} E{prime_line_length} F{Sp}

    # Retract and Z-hop
    G92 E0
    G1 E-0.2 F2100
    G92 E0
    G1 Z3 F{Sz}
    M400

    {% if ercf_enabled and printer.ercf.enabled|int == 1 %}
       {% if clog_detection > 0 %}
            {% if verbose %}
                RESPOND MSG="Reactivate ercf HH clog detection after primeline"
            {% endif %}
            ERCF_TEST_CONFIG enable_clog_detection={clog_detection}
        {% endif %}
	{% elif ercf_enabled %}
		{% if printer.ercf.clog_detection|int == 1 %}
            {% if verbose %}
                RESPOND MSG="Reactivate encoder sensor for Clog detection +/- EndlessSpool"
            {% endif %}
            SET_FILAMENT_SENSOR SENSOR=encoder_sensor ENABLE=1
        {% endif %}
    {% endif %}
```
But i thing nobody use klippain ercf with clog detection because there is a bug on START_PRINT too if someone use it

**Comment by Surion79** [comment]
`printer.ercf.clog_detection` works in stock ercf? i don't have it, so i can't check it.

**Comment by Benoitone** [comment]
> `printer.ercf.clog_detection` works in stock ercf? i don't have it, so i can't check it.

Yes, with notoolhead version that is use in klippain.

https://github.com/EtteGit/EnragedRabbitProject/blob/no_toolhead_sensor/Klipper_Files/client_macros.cfg

**Comment by Surion79** [comment]
ah, good to know, so that is universal usable

**Comment by Benoitone** [comment]
> ah, good to know, so that is universal usable

Not for the version with toolhead sensor (the original one...) 🥲

**Comment by Surion79** [comment]
i think we can close this now, since we do a general ercf rework now?

**Comment by Frix-x** [comment]
I'll close it for now in favor of the global ERCF rework :)

**Pull request closed without merging**
