### PR TITLE
Fix error with turning on filter only if it was used during printing.

### PR DESCRIPTION
**Pull request by tehniemer**
Fixed issue discovered after merging https://github.com/Frix-x/klippain/pull/380

### CODE REVIEW

**Comment by Surion79** [comment]
does this work?

**Comment by tehniemer** [comment]
Yes, @Benoitone and I have tested it.

**Comment by tehniemer** [comment]
I also added this to the `cancel_print` macro. I don't know why it wouldn't be desired there as well.

**Comment by tehniemer** [comment]
OMG, I don't know why my main branch keeps merging into these PR branches and screwing up the history.

**Comment by Surion79** [comment]
I would like to check this. The coding seems not optimal for me.
Especially that it is fixed on a hard coded fan name in a read only macro. That is not generic

**Comment by Benoitone** [comment]
> I would like to check this. The coding seems not optimal for me.
> Especially that it is fixed on a hard coded fan name in a read only macro. That is not generic

I still think that this is the easiest way to stop the nevermore which is also hard coded in a read-only file?
Maybe you have a better idea?

**Comment by Surion79** [comment]
Klippain is generic and has multiple fan options. I need to dig in, and i think there is a more genetic solution.

**Comment by Frix-x** [comment]
> I would like to check this. The coding seems not optimal for me. Especially that it is fixed on a hard coded fan name in a read only macro. That is not generic

I agree with Benoit on this point since it's also us that define this name in read-only files so there is unlikely someone that would change it (and if it does, every SET_FILTER macro will stop to work also... so it would be to define his own thing).
I'll merge it like this as it's ok for me :)

**Review by Frix-x — APPROVED** [review]

**Comment by tehniemer** [comment]
> Klippain is generic and has multiple fan options. I need to dig in, and i think there is a more genetic solution.

I think this is likely the most generic way to execute this. It should even catch the case where a user manually turns the filter on during a print.

**Pull request merged**
