### PR TITLE
Barf stealthburner leds integration

### PR DESCRIPTION
**Pull request by smwoodward**
I've attempted to integrate https://github.com/julianschill/klipper-led_effect into Klippain.  I'm not 100% sure if this is formatted the way that you would want it formatted, and it certainly could use some edits to get it the way that you want it with Klippain, but this should get it started for https://github.com/Frix-x/klippain/issues/142 and https://github.com/Frix-x/klippain/issues/164

### CODE REVIEW

**Comment by Surion79** [comment]
I am not sure that it is a good idea to have a hard dependency on another repo in the install script for a non default function.
Klippain also supports HappyHare but does not install it with klippain installation

**Comment by Surion79** [comment]
Klippain includes already large portion of this PR, just in a different place. Also it feels strange to move whole sections of existing configuration away in a different file. Also I don't like opening up a whole new folder just for another repo.

For me the positive thing is that STATUS_LEDS is called in some places, which weren't used before. But keep in mind, that having something finished and started next right away with "start led" color, will result in strobe light flash, since the time between previous end color and start color of the next activity is like a couple milliseconds.

**Comment by smwoodward** [comment]
> I am not sure that it is a good idea to have a hard dependency on another repo in the install script for a non default function. Klippain also supports HappyHare but does not install it with klippain installation

That's a fair point.

**Comment by smwoodward** [comment]
> Klippain includes already large portion of this PR, just in a different place. Also it feels strange to move whole sections of existing configuration away in a different file. Also I don't like opening up a whole new folder just for another repo.
> 
> For me the positive thing is that STATUS_LEDS is called in some places, which weren't used before. But keep in mind, that having something finished and started next right away with "start led" color, will result in strobe light flash, since the time between previous end color and start color of the next activity is like a couple milliseconds.

The new folder I figured would be best to have all of the customizable color shows in it and keep it away from other files.  That way it couldn't get messed up by accident if it was in variables or overrides, especially since they are so large.  I also made it serveral different config files to attempt to make it where if you are also using neopixel case lights, it would give some customization.  For example I have 3 neopixel strips, BARF on stealthburner and the nozzle lights, and I use the center strip as an extension of the BARF for status indication.

I don't think I moved large portions of existing configurations out of the setups, I did add the different things for klipper led effects.  I could be wrong, but that's why I wanted to open the PR is to get some help and collaborate on it.  I know it likely needs quite a bit of work.

**Comment by smwoodward** [comment]
You mentioned something about the led's strobing/flashing.  I've been using the klipper-led_effects for quite a while now and I've never noticed flashing when changing scenes.  I think it might be based on how that module handles changes.

**Comment by Surion79** [comment]
If you don't mind i would create an own PR and try to integrate a bit more in klippain as it is done with other integrations.

**Comment by smwoodward** [comment]
I do see how this PR has the fix for save_config for the z_offset and not just the barf integration.  I'll see if I can change the PR to fix that.

With that said, I did integrate the BARF things as much as I could tell of how klippain does it's other integrations.  If I'm missing something, can you give me a better example?

**Comment by Surion79** [comment]
I would first see to have a general led_effect integration which could be enabled by uncommenting a line in the printer.cfg. Not sure if barf stealthburner is required. Issue would be that it probably collides with the other led integrations. 
But need to see how to integrate in a more generic way.
(And copying existing config files to other read only sections is bad.)

**Comment by smwoodward** [comment]
> I would first see to have a general led_effect integration which could be enabled by uncommenting a line in the printer.cfg. Not sure if barf stealthburner is required. Issue would be that it probably collides with the other led integrations. But need to see how to integrate in a more generic way. (And copying existing config files to other read only sections is bad.)

The original status_led.cfg is still there, I have added the barf in addition to it.  But what did I copy from an existing config file and put it in another section?

Right now barf uses klipper-led_effect and is a separate setup compared to the original status_led setup and you wouldn't be able to use both of them at the same time, as they are different hardware required.  Currently, this wouldn't interact with other LED setups like neopixel caselights, but I am going to try and expand the klipper-led_effect to be able to handle variable caselight setups.  I am currently using this on my klippain setup in a bit of a different form.  

But there is already a general led_effect integration in the printer.cfg, this is a separate integration.

**Comment by smwoodward** [comment]
Actually, looking at this, it appears that some of the ideas that I was trying to put in place didn't get pull properly.  So I'm going to close this and figure out what happened.

**Pull request closed without merging**
