### PR TITLE
V0 Display and Menu config

### PR DESCRIPTION
**Pull request by Elias23**
Goals:
- Add support for the V0 Display which has it's own MCU
- Add Macros to shut down printer and host via display
- Adapt the display menu system to use the klippain macros
- (Optional boot logo code)

### Screen Menu:
_Italic added or changed_

Main:
   + Tune
       + Speed: 000%
       + Flow: 000%
       + Offset Z:00.00
   + ~~OctoPrint~~
       + ~~Pause printing~~
       + ~~Resume printing~~
       + ~~Abort printing~~
   + SD Card
       + Start printing
       + _Resume printing_
       + _Pause printing_
       + _Cancel printing_
       + ... (files)
   + Control
       + _Park toolhead_
       + Home All
       + Home Z
       + Home X/Y
       + Z Tilt
       + Quad Gantry Lvl
       + Bed Mesh
       + Steppers off
       + Fan: OFF
       + Fan speed: 000%
       + _Lights: OFF_
       + _Lights: 000%_
       + Move 10mm
           + Move X:000.0
           + Move Y:000.0
           + Move Z:000.0
           + Move E:+000.0
       + Move 1mm
           + Move X:000.0
           + Move Y:000.0
           + Move Z:000.0
           + Move E:+000.0
       + Move 0.1mm
           + Move X:000.0
           + Move Y:000.0
           + Move Z:000.0
           + Move E:+000.0
   + Temperature
       + Ex0:000 (0000)
       + Ex1:000 (0000)
       + Bed:000 (0000)
       + Preheat PLA
           + Preheat all
           + Preheat hotend
           + Preheat hotbed
       + Preheat ABS
           + Preheat all
           + Preheat hotend
           + Preheat hotbed
       + Cooldown
           + Cooldown all
           + Cooldown hotend
           + Cooldown hotbed
   + Filament
       + Ex0:000 (0000)
       + _Load Filament_
       + _Unload Filament_
       + _Purge Filament_
       + _Clean Nozzel_
       + ~~Load Fil. fast~~
       + ~~Load Fil. slow~~
       + ~~Unload Fil.fast~~
       + ~~Unload Fil.slow~~
       + Feed: 000.0
   + Setup
       + Save config
       + Host control~~Restart~~
           + Restart host
           + Restart FW
           + _Shutdown host_
       + PID tuning
           + Tune Hotend PID
           + Tune Hotbed PID
       + Calibration
           + Delta cal. auto
           + Delta cal. man
               + Start probing
               + Move Z: 000.00
               + Test Z: ++
               + Accept
               + Abort
           + Bed probe
       + Dump parameters

### CODE REVIEW

**Comment by Surion79** [comment]
please keep the base on develop. the merge is never done on main directly

**Comment by Frix-x** [comment]
Hi, thanks for this PR! I'll review it soon but it look like a very good base :)

**Comment by Frix-x** [comment]
Hello, I'm back to it! This is pretty good. I just would like to know if you could make a video or something of the boot logo since it's pretty hard to vizualize it using this file without the screen on hand ^^

Also can you change the "OFF" macro to "_OFF". I don't think it's necessary to make it available as a new macro for everyone since it could confuse people about what is its purpose

**Comment by Frix-x** [comment]
Thanks for the video. I understand better now. That's pretty nice indeed!

I played a bit with the Klippain logo and converted it to a "glyph" format as best as I could. However, I'm not sure to understand how to split it for Klipper. But if you know it, here is the full Glyph for a 128x64 display:

```
..................................**********************......**.........************************...****************...*********
.................................***********************................*************.....*******...**************...***********
.................................***********************..**............*********............*****...*********.....*************
................................************************..****..........*******................***...............***************
................................*************************..****........******......***...**.....**...........******************.
...............................***************************.*****......*****.....*****...*****....**......*********************.*
...............................***************************..****......*........*****..*.******....*......*******************..**
...............................***************************...***..............******.*.********........********************..***
..............................****************************.....*.............******.**.*********........******************..***.
..............................****************************.............***..******.**..*********........****************..****..
..........................*...*****************************..........****..*******.**.**********........**************...***....
.....................******...*****************************..*.****..***.*.*******.**.**********........************...****.....
.............**************...**************************.....*.****..**.*..*******.*..***********.......**********...*****......
.......********************..*************************.......*.****..*.**.********...************.................******.......*
....***********************..************************........*.****..*.**.********...***********..............********........*.
.**************************..***********************....***..*.****..*.*..********..************........***********..........*..
**************************...******************.......***....*.****..*.*..********.*************........*******............**...
**************************...***************.........***.......***...*.*.**********************....*......................*.....
**************************...*************..........****.*.*........**...*********************.....*....................**......
**************************...************......***..***.*..**.......**..*********************......*..................**........
**************************...**********.....****...***.**.****....****..********************......**...............***..........
************************.....*********.....****....***.**.************.*******************........**........*******.............
********************.........********....******.*.****.*..******************************.........**.....*****...................
****************.............****.......******.*..****.*.****************************...........***.............................
************......*******.....*.........*****.**.****.**.**************************............***..............................
**********...**************.........*..******.**.****....************************..............**...............................
********...****************......***...******.**.*****..***********************...............***...............................
******...******************....****...*******.*..*****.*********************..................**................................
*****..*******************....****.*..*******.*.******.*******************...................***................................
****..*******************....*****.*.********.*.************************.....................*..................................
***..********************...*****.**.********..**********************.......................*...................................
**.**********************...*****.**.********..********************.............................................................
*..*********************...******.*..********.*******************..........................*....................................
..*******************......******.*.***************************...........................*.....................................
.*****************.........******...************************.............................*......................................
***************....****....******..***********************..............................*.......................................
*************....****......******..*********************...............................*........................................
************...****........******.*******************.................................*.........................................
***********..***...........************************..................................*..........................................
**********.****............**********************...................................*...........................................
*********.***...............*******************...................................**............................................
********.***.................***************....................................**..............................................
*******.***...................************......***...........................**................................................
******.***......................*******............***......................**..................................................
******.***............................................*****.............****....................................................
*****.***..................*.*..............................***********.........................................................
****..**..................*.....................................................................................................
****.***...............**.......................................................................................................
***..**...............*.........................................................................................................
***.***..............*..........................................................................................................
***.**..............*.......***....***..***.......***..*****....******.......***......***..***.....***..........................
**.***............*.........***..*****..***.......***.*******..********.....****......***..****....***..........................
**.***...........*..........***.*****...***.......***.********.*********....*****.....***..*****...***..........................
*..**............*..........********....***.......***.***...**.***...***...******.....***..******..***..........................
*.***...........*...........*******.....***.......***.***...**.***...***...**..***....***..*******.***..........................
*.***..........*............******......***.......***.********.********...***..***....***..***********..........................
..**..........*.............*******.....***.......***.*******..********...*********...***..***.*******..........................
.***........................***.****....***.......***.*****....******....**********...***..***..******..........................
.***.........*..............***..****...***.......***.***......***.......***********..***..***...*****..........................
.**.........*...............***...****..********..***.***......***......****.....***..***..***....****..........................
***.........*...............***....***..********..***.***......***......***......****.***..***.....***..........................
***........*................***.....**..********..***.***......***......**........***.***..***.....***..........................
***........*....................................................................................................................
**........*.....................................................................................................................
```

And here is the black and white picture for reference of what it should give you :)
image

**Comment by Frix-x** [comment]
Wooooow this is so cool! Thank you for your devotion, I can definitely understand the pain it was to convert it to the Klipper format 😆

**Comment by Frix-x** [comment]
Hello @Elias23 , I'm reviewing the PR and I think I'm good for a first merge. We can always make it evolve more in the future but it's a very good first step!

If it's ok for you, can you update the base branch and fix the conflicts? I think it's about the LED system that was reworked a bit in the develop branch to allow led_effects, etc...

Thank you :)

**Comment by Elias23** [comment]
@Frix-x I fixed the conflicts and integrated boot-logo better with the startup macro

**Review by Frix-x — APPROVED** [review]
Thank you for your work!

I'll merge it to the develop branch in a couple of minutes to be released with the next Klippain version :)

**Pull request merged**
