### PR TITLE
Fix Error in ERCF clog detection in primeline

### PR DESCRIPTION
**Pull request by Benoitone**
i think there is an error in check clog detection for reactivated it in prime line module??

### CODE REVIEW

**Comment by Benoitone** [comment]
clog variables

**Comment by Benoitone** [comment]
clog variables

**Comment by Surion79** [comment]
i do have clog detection after prime line.
what is your point? you are refering to the config file, not the real loaded value.
This is works exactly as expected.

**Comment by Benoitone** [comment]
Ho yes i Forget this... thanks

**Pull request closed without merging**
