### PR TITLE
variable.cfg setting to control cale leds at startup

### PR DESCRIPTION
**Pull request by claudioguareschi**
As above

### CODE REVIEW

**Comment by Benoitone** [comment]
Can you make this PR only based on the new branch leds-rework?

**Comment by claudioguareschi** [comment]
> Can you make this PR only based on the new branch leds-rework?

Be glad to do that but I need some guidance on how to do it. I am not good with github stuff. If you can give me a little help will be glad to streamline this as much as possible

**Comment by Benoitone** [comment]
> > Can you make this PR only based on the new branch leds-rework?
> 
> Be glad to do that but I need some guidance on how to do it. I am not good with github stuff. If you can give me a little help will be glad to streamline this as much as possible

for exemple in your own klippain fork repo create a new branch name for exemple `leds_rework` like that:
fork repo
and then you can modify this branch to create your PR in Klippain.

**Comment by claudioguareschi** [comment]
Thanks, done

**Comment by Frix-x** [comment]
I'm closing this since there was a big merge done in the develop with all the work you've done already and some minor modifications :)
Thank you very much for the work!

If you think it's not perfect, I'll let you open a new PR against the latest version in develop to start from a clean repo, it will be easier :)

**Pull request closed without merging**
