### PR TITLE
nevermore-controller for StealthMax and Nevermore Max

### PR DESCRIPTION
**Pull request by qratz**
add configuration for nevermore controller from https://github.com/Sa…naaHamel/nevermore-controller as used in Nevermore Max and Nevermore StealthMax

### CODE REVIEW

**Comment by Surion79** [comment]
I am not sure if it is ok to add config files which are basically completely commented out. usually including files have some sort of basic functionality which can be used out of the box.
In your integration, if i uncomment the file for the nevermore, the end_print will always trigger the nevermore command instead of the correct SPEED=0 command for the other nevermore filter. 
This stage feels a bit more like being implemented in override for the people who uses it, since it needs to be fully overridden anyway.

**Comment by qratz** [comment]
I think you are right. The nevermore-controller essentially acts autonomously, which makes it a very nice solution. So just adding the [nevermore] section in overrides, enabling filter and setting the correct filtername in variables.cfg is all that is needed to enable the filter with the expected behaviour.

**Comment by Frix-x** [comment]
Thanks for the discussion about this!
So I think for now nothing more needs to be added to Klippain? If this is the case, I'll close the PR :)

**Comment by qratz** [comment]
Yes, the PR can be closed. Maybe it someone could add information on how to use nevermore-controller in one of the MD-Files.

**Comment by Frix-x** [comment]
> Maybe it someone could add information on how to use nevermore-controller in one of the MD-Files.

Yes this is a good idea. If you want to open a PR with some documentation, I'll be happy to merge it :)

**Pull request closed without merging**
