### PR TITLE
Support for TMC5160 on Z Axis

### PR DESCRIPTION
**Pull request by reineruhry**
Added Support for TMC5160 on Z axis, specially for BTT Manta M8P + Voron 2.4.

### CODE REVIEW

**Review by Surion79 — APPROVED** [review]
looks good for me

**Review by Frix-x — APPROVED** [review]

**Comment by Frix-x** [comment]
Sorry I've done an update of the base branch. Can you rebase your work on the latest develop commit? Thanks

**Comment by reineruhry** [comment]
rebased!

**Review by Frix-x — APPROVED** [review]

**Comment by Frix-x** [comment]
Thanks, merged :)

**Pull request merged**
