### PR TITLE
ADD LDO_Nighthawk-SB Toolhead

### PR DESCRIPTION
**Pull request by mvdveer**
I mapped the LDO_Nighthawk-SB toolbar to work with Klippain. Three files were added: /config/mcu_definitions/toolhead/LDO_Nighthawk-SB_v1.0 
 /user_templates/mcu_definitions/toolhead/LDO_Nighthawk-SB_v1.0
/macros/hardware_functions/tacho_macros.cfg

Used the LDO GitHub example configuration files to add a section on thermistors.

The mapping was done on the template from the Mellow Fly sb2040 Canbus board. (this is because the LDO- board replaced that board and I wanted an easy integration)

### CODE REVIEW

**Comment by Surion79** [comment]
can you elaborate why macros are required for adding toolhead configuration? PRs should only include one functional change, not multiples.

**Comment by mvdveer** [comment]
> can you elaborate why macros are required for adding toolhead configuration? PRs should only include one functional change, not multiples.

Sorry as I have not done a PR before, I was unaware of this. I can remove it if you want. Here is why:

As per the LDO documentation, (https://docs.ldomotors.com/en/voron/nitehawk-sb)  this macro is optional when the Fan tacho function is enabled:

"Provided in the github [repo](https://github.com/MotorDynamicsLab/Nitehawk-SB/tree/master/Firmware/Klipper%20Configs) is an optional tacho_macros.cfg file which contains the macro PREFLIGHT_CHECK. This macro very briefly turns on the part fan and checks the tachometer signal to see if the fan is spinning properly. To use the macro, [include tacho_macros.cfg] in printer.cfg and call PREFLIGHT_CHECK at the beginning of the PRINT_START macro:

**Comment by akashrpatel** [comment]
@mvdveer There are a number of typos and errors in your uploaded files...I've fixed the issues and attached file here

[LDO_Nighthawk-SB.zip](https://github.com/Frix-x/klippain/files/14395263/LDO_Nighthawk-SB.zip)

**Comment by Frix-x** [comment]
Thanks @mvdveer for your PR. I will merge it to a temporary branch to allow me to edit it a little bit before merging it by using @akashrpatel suggestions.

Thank you, hopefully we will be able to merge it for the next version :)

**Pull request merged**
