### PR TITLE
Create BTT_Octopus_Max.cfg

### PR DESCRIPTION
**Pull request by smwoodward**
I created a board definition file for the BTT Octopus Max board

### CODE REVIEW

**Comment by Surion79** [comment]
@smwoodward Thanks! Can you please also add the mcu default template for this board? The pin assignment alone is not enough for Klippain.
You can find them in the repo under user_templates/mcu_defaults/main
It could be enough to just use the BTT_Octopus.cfg as base and continue from there

**Comment by smwoodward** [comment]
Yeah I'll try and get this done asap

**Comment by jelkand** [comment]
I have set up an octopus max on my printer and I'm happy to pick this up and take it to the finish line. Let me know the preferred way of doing that--new PR, commits to this branch, etc.

**Comment by Frix-x** [comment]
> I have set up an octopus max on my printer and I'm happy to pick this up and take it to the finish line. Let me know the preferred way of doing that--new PR, commits to this branch, etc.

Thanks for your help. I will merge this PR into a special develop branch where you will be able to add your PR ontop if you are ok? This way we will keep the contribution of smwoodward :)

**Comment by Frix-x** [comment]
Done: I let you push your additional work into https://github.com/Frix-x/klippain/tree/develop-octopusmax

**Comment by jelkand** [comment]
Thank you. I will be working on that this weekend.

**Pull request merged**
